<?php

namespace Ip\AttractifBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{
    public function getMostPurchased()
    {
        return $this->createQueryBuilder("pur")
            ->addSelect('SUM(pur.quantity) as total')
            ->addSelect('pur')
            ->leftJoin('pur.product', 'prod')
            ->addSelect('prod')
            ->setMaxResults(10)
            ->orderBy("total", "DESC")
            ->groupBy("prod.name")
            ->getQuery()
            ->getResult();
    }
}
