<?php

namespace Ip\AttractifBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends EntityRepository
{
    public function findWithEventByStatus($status, $evenId)
    {
        return $this->createQueryBuilder("r")
            ->where('r.event = :id')
            ->setParameter('id', $evenId)
            ->andWhere('r.status = :status')
            ->setParameter('status', $status)
            ->getQuery()
            ->getResult();
    }

    public function findRandomDQL($number, $id)
    {
        $query = $this->_em->createQuery('SELECT r FROM IpAttractifBundle:Request r WHERE r.event = :id');
        $query->setParameter('id', $id);

        return $query->getResult();
    }
}
